### ISSUE TITLE
parents is undefined in the example node G

### ISSUE THREAD

**Issue by roiros** [NilsBaumgartner1994/Netzplan#2]
https://github.com/NilsBaumgartner1994/Netzplan/blob/2f55b057adff5d30a949752e98471fa6860039b1/index.js#L122

better to replace it with `if (parents){ for loop}` or `if (!parents) {continue}`

**Comment by NilsBaumgartner1994** [comment]
Fixed
project will be renewed with CI/CD and tests

**Comment by NilsBaumgartner1994** [comment]
Found another bug where i had checked for !start where startDate could be 0 which would be false in the backward calculation.

I setup a new project. https://github.com/FireboltCasters/PrecedenceDiagramMethod
There I also added a Demo in which the calculation can be done interactivly.

I will delete this project when i have documented the new package good enough.

**Comment by NilsBaumgartner1994** [comment]
Finished this project: https://github.com/FireboltCasters/PrecedenceDiagramMethod
